### PR TITLE
translated some turkish

### PR DESCRIPTION
**Pull request by YoruNoKen**
## Tranlsation Info
- Author: YoruNoKen
- Translated Platform: `client`
- Translated Languages: Turkish(tr_tr)

## Description
Translated some of the Turkish sentences

### CODE REVIEW

**Review by RedLime — APPROVED** [review]

**Review by RedLime — CHANGES_REQUESTED** [review]
test

**Review by RedLime — APPROVED** [review]

**Review by RedLime — CHANGES_REQUESTED** [review]
@YoruNoKen could you change description?

**Comment by YoruNoKen** [comment]
changed, is that good? @RedLime

**Comment by RedLime** [comment]
oh I mean Tranlsation Info lol

**Comment by YoruNoKen** [comment]
> oh I mean Tranlsation Info lol

am I supposed to change translated languages and author? @RedLime

**Comment by RedLime** [comment]
yes @YoruNoKen

**Comment by YoruNoKen** [comment]
aight done @RedLime

**Comment by RedLime** [comment]
waiting another approves now

**Review by RedLime — APPROVED** [review]

**Pull request merged**
